version: "3.4"
services: 
    nginx:
        image: nginx:alpine
        container_name: Boink_ecommerce-nginx
        restart: unless-stopped 
        ports:
            - 800:800
            - 4433:4433
        volumes:
            - ./:/var/www/html/:cached
            - ./.docker/nginx:/etc/nginx/conf.d
            - ./.docker/nginx/ssl:/etc/nginx/conf.d/ssl
        depends_on: 
            - app-fpm    
        networks:
            -  Boink_ecommerce-network
    app-fpm:
        build: 
            context: ./.docker/php
            dockerfile: Dockerfile
        container_name: Boink_ecommerce-app
        restart: unless-stopped
        volumes: 
            - ./:/var/www/html:cached
            - ./.docker/php/php-fpm.ini:/usr/local/etc/php/conf.d/custom.ini
            - ~/.ssh:/root/.ssh 
        depends_on:
            - mariadb
            - redis          
        networks:
            -  Boink_ecommerce-network
    mariadb:
        image: mariadb:10.5.5
        container_name: Boink_ecommerce-mariadb
        restart: unless-stopped
        ports: 
            - 4406:4406
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment: 
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=boink
            - MYSQL_PASSWORD=boink
            - MYSQL_DATABASE=boink
        networks:
            - Boink_ecommerce-network
    redis:
        image: redis:alpine
        container_name: Boink_ecommerce-redis
        volumes: 
            - ./data/redis:/data
        ports:
            - 6379:6379
        networks:
            - Boink_ecommerce-network             


networks:
    Boink_ecommerce-network:
        driver: bridge
volumes:
    Boink_ecommerce-volumen:
        driver: local